### ISSUE TITLE
Port to XenServer builder

### ISSUE THREAD

**Issue by sammcj** [sammcj/packer-qemu-debian-jessie#4]
I want to port this to the [XenServer](https://github.com/rdobson/packer-builder-xenserver) builder once these are fixed upstream:
- https://github.com/xenserverarmy/packer/issues/2
- https://github.com/xenserverarmy/packer/issues/3

cc/ @rdobson

**Comment by sammcj** [comment]
It might actually be worth looking at using https://github.com/xenserver/transfervm rather than the packer XenServer builder as that doesn't look to be going places very quickly.

**Comment by rdobson** [comment]
FYI - packer-builder-xenserver doesn't rely on NFS (your issue #2). Adding SSH key support is a good idea.

**Comment by sammcj** [comment]
Ok - Tim was saying that it did but he was working to remove that hard
coding.

## 

Sam McLeod
@s_mcleod[https://twitter.com/s_mcleod] | smcleod.net
